# Generated by Django 3.2.10 on 2021-12-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
