# Generated by Django 3.2.10 on 2021-12-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20211209_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='flat_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bills',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bills',
            name='total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bills',
            name='charity_charges',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='bills',
            name='parking_charges',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='bills',
            name='sinking_fund_charges',
            field=models.IntegerField(default=80),
        ),
    ]
