# Generated by Django 3.2.10 on 2021-12-09 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20211209_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.profile'),
        ),
    ]
