# Generated by Django 3.2.10 on 2021-12-10 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0013_profile_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Month',
        ),
        migrations.AlterField(
            model_name='bills',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
