# Generated by Django 3.2.10 on 2021-12-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20211210_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='previous_dues',
            field=models.IntegerField(default=100, null=True),
        ),
    ]
