# Generated by Django 3.2.10 on 2021-12-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_bills_previous_dues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='previous_dues',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
