# Generated by Django 3.2.10 on 2021-12-10 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_bills_previous_dues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='flat_no',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='name',
        ),
        migrations.AlterField(
            model_name='bills',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bills',
            name='publish_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
