# Generated by Django 3.2.10 on 2022-03-01 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20211210_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=100)),
                ('visitor_phone', models.IntegerField()),
                ('visiting_flat', models.CharField(max_length=100)),
                ('visiting_date', models.DateField(default=datetime.date.today)),
                ('visiting_time', models.TimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
