# Generated by Django 3.2.10 on 2022-04-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='contact_name',
        ),
        migrations.AddField(
            model_name='complaint',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
