# Generated by Django 3.2.10 on 2022-04-06 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_complaint_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='publish_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
