# Generated by Django 3.2.10 on 2022-04-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_notice_publish_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
