# Generated by Django 3.2.10 on 2022-04-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('r', 'Resident'), ('s', 'Staff'), ('a', 'Superuser')], max_length=1, null=True),
        ),
    ]
