# Generated by Django 3.2.10 on 2022-04-18 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='showflag',
            field=models.CharField(blank=True, choices=[('y', 'Show'), ('n', 'Hide')], max_length=1),
        ),
        migrations.AddField(
            model_name='notice',
            name='showtill',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 19, 20, 16, 20, 70690)),
        ),
    ]
