# Generated by Django 3.2.10 on 2022-04-18 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20220418_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='resolve_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('y', 'Resolved'), ('n', 'Not Resolved')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='showtill',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 19, 23, 29, 13, 139200)),
        ),
    ]
