# Generated by Django 3.2.10 on 2022-04-19 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20220419_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='due_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='bills',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='notice',
            name='showtill',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 20, 13, 18, 28, 72181)),
        ),
    ]
