# Generated by Django 3.2.10 on 2022-04-28 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20220419_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='flat_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='showtill',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 29, 23, 8, 37, 116155)),
        ),
    ]
