# Generated by Django 3.2.10 on 2022-04-28 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20220428_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='bill_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='showtill',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 30, 1, 11, 18, 609615)),
        ),
    ]
